### ISSUE TITLE
Add Comment

### ISSUE THREAD

**Issue by SofiaNords** [SofiaNords/celiacs-api#14]
## Description
As a logged-in user, I want to add comments to a post so that I can share my thoughts about it.

## Acceptance Criteria
1. There is a visible “Add Comment” button or input field associated with each post.
2. Users can type their comments and submit them.
3. Comments are immediately visible to other users after submission.

### BE
- [x] Create Comment App
- [x] Create Comment Model
- [x] Create Comment Serializer & CommentDetail Serializer
- [x] Create Comment View & CommentDetail View

### FE
- [x] Create Comment Form and Page
