### ISSUE TITLE
Visitor View Posts

### ISSUE THREAD

**Issue by SofiaNords** [SofiaNords/celiacs-api#21]
## Description
As a visitor to the site, I want to be able to read other users’ posts so that I can understand the content and get a sense of what the page offers.

## Acceptance Criteria
1. The site provides a clear way to access posts created by other users.
2. Visitors can explore different posts easily.

### BE
- [x] Add Posts App
- [x] Create Posts model
- [x] Create Posts Serializer
- [x] Create PostList View
- [x] Create PostDetail View
- [ ] Notes in README
### FE
- [x] Create Post From
- [x] Set up Post Page
- [x] Create Post Component
