### ISSUE TITLE
Select and Unselect Posts

### ISSUE THREAD

**Issue by SofiaNords** [SofiaNords/celiacs-api#25]
## Description
As a logged-in user, I want to be able to select and unselect other users’ posts so that I can manage my list of selected posts.

## Acceptance Criteria
1. Each post displays a selectable checkbox or toggle.
2. Clicking the checkbox selects or unselects the post.
3. I can easily remove selected posts from my list.

### BE
- [x] Add Select App
- [x] Create Select Model
- [x] Create Select Serializer
- [x] Create Select View
- [x] Add select_id  to PostSerializer

### FE
- [x] Add Select and Unselect feature to Post page
