### ISSUE TITLE
View own Profile

### ISSUE THREAD

**Issue by SofiaNords** [SofiaNords/celiacs-api#26]
## Description
As a user, I want to view my own profile so that I can see the posts I've posted.

## Acceptance Criteria
1. There is a dedicated “My Profile” section accessible from the navigation menu.
2. My profile page displays a list of posts I have posted.
3. I can quickly navigate to this page from any part of the site.

## Tasks BE
- [x] Add Profiles App
- [x] Create Profiles model 
- [x] Create Profile Serializer
- [x] Create Profile ListView
- [x] Notes in README

## Tasks FE
- [x] Create Profile Page
