### ISSUE TITLE
Score post

### ISSUE THREAD

**Issue by SofiaNords** [SofiaNords/celiacs-api#39]
## Description
**As a **user ,** I want** to rate my post, **So that** other users can see how satisfied I was with the experience.

## Acceptance Criteria
1. The user must be able to see a rating options when creating their post.
2. The user must be able to submit their rating with a single click or tap.
3. The user must be able to edit their rating after submission.
4. Invalid ratings should not be accepted and should prompt an error message.

## Tasks
###BE
- [x] Add Score to Post model and serializer

###FE
- [x] Add Score to Post.js
- [x] Add Score to PostEditForm.js
- [x] Add Score error handling
