### ISSUE TITLE
Categorise post

### ISSUE THREAD

**Issue by SofiaNords** [SofiaNords/celiacs-api#40]
## Description
**As a**  user , **I want** to be able to categorise my post, **So that** other users understand what kind of restaurant or café it is.

## Acceptance Criteria
1. The user must be able to see a list of predefined categories (e.g., Restaurant, Café, Bakery, etc.).
2. The user must be able to select one category for their post.
3. The selected category must be displayed on the post.
4. Other users must be able to see the category associated with the post.
5. The user must be able to edit the category of their post after it has been published.
6. The updated categories should be reflected immediately on the post.
7. Invalid or empty category selections should prompt an error message.
8. The category selection process should be intuitive and user-friendly.

## Tasks
###BE
- [x] Create category app and model
- [x] Create CategorySerializer, views & urls
- [x] Add category to post model & PostSerializer

###FE
- [x] Add category in Post.js and PostCreateForm.js
- [ ] Add category in PostEditForm.js
- [x] Add category error handling in PostCreateForm.js and PostEditForm.js
